name: Fortnite Shop TANROX

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install requests pillow

      - name: Ejecutar tienda
        run: python shop.py
        env:
          FORTNITE_API_KEY: ${{ secrets.FORTNITE_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
